include:
  - project: accessable-net/gitlab-ci-templates
    file: pages.yml

build:
  stage: build
  image: node:alpine
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - dist
  cache:
    paths:
      - node_modules

pages:
  variables:
    BUILD_OUTPUT_PATH: ${CI_PROJECT_DIR}/dist
